# Generated by Django 5.0.4 on 2024-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('display', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('price_blr', models.IntegerField()),
            ],
        ),
    ]
